#!/bin/bash
# Mounting Script for connecting to the Network_Drive	
#####
# Load config files
#####
source config

#####
# Create folder if it doesn't exist
#####
if [ ! -d $NETWORKDRIVEDIR ]; then
    mkdir $NETWORKDRIVEDIR
fi

#####
# Attempt to mount drive multiple times
#####
for i in {0..10}
do
    mount -t smbfs smb://srv008/Students/`whoami` $NETWORKDRIVEDIR
    if [ `echo $?` -eq 0 ]; then
        break
    fi
    sleep 5
done
