#!/bin/bash
## Script creates new Vagrantfile with correct specifications
###
## Create a custom Vagrantfile with our settings
## Everything from cat <<EOF to EOF goes into Vagrantfile
###
cat <<EOF > /Users/`whoami`/vagrant_synced/Vagrantfile
# Written in Ruby ,(o.0)'

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

###
## Sync and mount network drive into vagrant box
###
  config.vm.synced_folder "/Users/`whoami`/network_drive", "/home/vagrant", type: "rsync",
    rsync__verbose: true,
    rsync__exclude: [".ssh/", ".bashrc", ".bash_on_exit"]

  config.vm.synced_folder "/Users/`whoami`/network_drive", "/home/.private_share"

###
## Run intialization script to set up ~/.bash_profile
## Executes on vagrant up and/or vagrant provision
###
  config.vm.provision "shell", path: "2-RunOnProvision"
end
EOF
