#!/bin/bash
## Script executes every time you provision your box
###
###
## Commands that you'd like run when the machine boots:
###
sudo apt-get -y update
sudo apt-get -y install git
sudo apt-get -y install emacs

#... and so on 





cat <<EOF >/home/vagrant/.bash_profile
source /home/vagrant/.bash_on_exit
source /home/vagrant/.bashrc
###
## Everything below until EOF will be your environment configuration.
## Include aliases, functions, PS1 variables, etc here.
###
alias ls='ls --color=auto'
alias grep='grep --color=auto'

PS1='\u @ \w $'

betty () {
    echo "hmmm this could be pretty useful..."
}

# and so on and so on...







EOF
cat <<EOF >/home/vagrant/.bash_on_exit
###
# This function will resync your files to the network drive on exit.
# Do not touch unless you know what your doing! 
###
executeOnExit() {
    nohup rsync -vra --exclude=".ssh" /home/vagrant/ /home/.private_share & 2> /dev/null
}
trap executeOnExit EXIT
EOF
