#!/bin/bash
## Mounting Script for connecting to the Network_Drive
###
###
## Create folder if it doesn't exist
###
if [ ! -d /Users/`whoami`/network_drive ]; then
    mkdir /Users/`whoami`/network_drive
fi

###
## Attempt to mount drive multiple times
###
for i in {0..100}
do
    echo "Mounting network drive to /Users/`whoami`/network_drive..."
    mount -t smbfs smb://srv008/Students/`whoami` /Users/`whoami`/network_drive
    if [ `echo $?` -eq 0 ]; then
        break
    fi
    mount -t smbfs smb://srv008/Students/`whoami` /Users/`whoami`/network_drive
    if [ `echo $?` -eq 64 ]; then
        echo "File Exists is OK! That means your drive is mounted."
        break
    fi
    echo "Sometimes the network doesn't work (._.)"
    echo "Try restarting or use another mac? ¯\_(ツ)_/¯"
    echo "If you need to use this specific machine, just run:"
    echo "./2-Vagrantscript && vagrant up && vagrant ssh"
    echo "FAIR WARINING: your files will not correctly sync! (use github!)"
    sleep 10
done

###
## Remove vagrant_synced folder and pull new copy
###
rm -rf /Users/`whoami`/vagrant_synced

###
## Pull a fresh copy either from USER specified, or from master branch
###
git clone https://anon:anon@github.com/$1/vagrant_setup /Users/`whoami`/vagrant_synced 2> /dev/null ||
{ echo "######################################################" &&
echo "Github USERNAME not given, cloning a basic master copy" &&
echo "Usage: ./launch_vagrant USERNAME" &&
echo "######################################################" &&
git clone https://anon:anon@github.com/j-tyler/vagrant_setup /Users/`whoami`/vagrant_synced 2> /dev/null; }

/Users/`whoami`/vagrant_synced/1-VagrantSetup 
export VAGRANT_CWD=/Users/`whoami`/vagrant_synced/
vagrant provision && vagrant up && vagrant ssh 
