#!/bin/bash
##Pulls a fresh copy of setup from your github or master branch
###
## Remove vagrant_synced folder and pull new copy
###
rm -rf /Users/`whoami`/vagrant_synced
 
###
## Pull a fresh copy either from USER specified, or from master branch
###
git clone https://github.com/$1/vagrant_setup /Users/`whoami`/vagrant_synced 2> /dev/null ||
echo "######################################################" &&
echo "Github USERNAME not given, cloning a basic master copy" &&
echo "Usage: ./launch_vagrant USERNAME" &&
echo "######################################################" &&
git clone https://github.com/j-tyler/vagrant_setup /Users/`whoami`/vagrant_synced 2> /dev/null
